<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Disaster Alert System - Analytics Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #e74c3c;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #e74c3c;
            font-size: 24px;
            margin: 0;
        }
        .header .subtitle {
            color: #666;
            font-size: 14px;
            margin-top: 5px;
        }
        .meta-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 5px;
        }
        .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .section-title {
            background: #3498db;
            color: white;
            padding: 10px 15px;
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 15px;
            border-radius: 3px;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 15px;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            padding: 15px;
            background: #f8f9fa;
            border: 1px solid #dee2e6;
            text-align: center;
        }
        .stat-value {
            font-size: 28px;
            font-weight: bold;
            color: #3498db;
        }
        .stat-label {
            color: #666;
            font-size: 12px;
            margin-top: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        table.data-table th {
            background: #34495e;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
        }
        table.data-table td {
            padding: 8px 10px;
            border-bottom: 1px solid #dee2e6;
        }
        table.data-table tr:nth-child(even) {
            background: #f8f9fa;
        }
        .summary-table {
            width: 100%;
            margin-bottom: 15px;
        }
        .summary-table td {
            padding: 8px;
            border-bottom: 1px dotted #ddd;
        }
        .summary-table td:first-child {
            font-weight: bold;
            width: 200px;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-critical { background: #e74c3c; color: white; }
        .badge-high { background: #f39c12; color: white; }
        .badge-moderate { background: #f1c40f; color: #333; }
        .badge-low { background: #95a5a6; color: white; }
        .badge-active { background: #27ae60; color: white; }
        .badge-pending { background: #f39c12; color: white; }
        .badge-completed { background: #27ae60; color: white; }
        .progress-bar {
            width: 100%;
            height: 20px;
            background: #ecf0f1;
            border-radius: 10px;
            overflow: hidden;
            position: relative;
        }
        .progress-fill {
            height: 100%;
            background: #3498db;
            text-align: center;
            color: white;
            font-size: 11px;
            line-height: 20px;
        }
        .alert-box {
            background: #fff3cd;
            border-left: 4px solid #f39c12;
            padding: 15px;
            margin-bottom: 15px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e74c3c;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>🚨 DISASTER ALERT SYSTEM</h1>
        <div class="subtitle">Analytics & System Report</div>
    </div>

    <!-- Meta Information -->
    <div class="meta-info">
        <table>
            <tr>
                <td><strong>Report Generated:</strong> {{ $generated_at }}</td>
                <td style="text-align: right;"><strong>Generated By:</strong> {{ $generated_by }}</td>
            </tr>
        </table>
    </div>

    <!-- Executive Summary -->
    <div class="section">
        <div class="section-title">📊 EXECUTIVE SUMMARY</div>
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-value">{{ $alerts['total'] }}</div>
                <div class="stat-label">Total Alerts</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $shelters['total'] }}</div>
                <div class="stat-label">Total Shelters</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $requests['total'] }}</div>
                <div class="stat-label">Total Requests</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $requests['total_people'] }}</div>
                <div class="stat-label">People Affected</div>
            </div>
        </div>
    </div>

    <!-- Alerts Section -->
    <div class="section">
        <div class="section-title">🚨 ALERTS ANALYSIS</div>
        
        <table class="summary-table">
            <tr>
                <td>Total Alerts</td>
                <td>{{ $alerts['total'] }}</td>
            </tr>
            <tr>
                <td>Active Alerts</td>
                <td><span class="badge badge-active">{{ $alerts['active'] }}</span></td>
            </tr>
            <tr>
                <td>Resolved Alerts</td>
                <td>{{ $alerts['resolved'] }}</td>
            </tr>
        </table>

        <h4 style="margin-top: 20px; margin-bottom: 10px;">By Severity:</h4>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Severity Level</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($alerts['by_severity'] as $severity => $count)
                <tr>
                    <td>
                        <span class="badge badge-{{ strtolower($severity) }}">{{ $severity }}</span>
                    </td>
                    <td>{{ $count }}</td>
                    <td>{{ $alerts['total'] > 0 ? round(($count / $alerts['total']) * 100, 1) : 0 }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <h4 style="margin-top: 20px; margin-bottom: 10px;">By Type:</h4>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Alert Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($alerts['by_type'] as $type => $count)
                <tr>
                    <td>{{ $type }}</td>
                    <td>{{ $count }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Shelters Section -->
    <div class="section">
        <div class="section-title">🏠 SHELTERS CAPACITY REPORT</div>
        
        <div class="alert-box">
            <strong>Overall Occupancy Rate: {{ $shelters['occupancy_rate'] }}%</strong><br>
            <div class="progress-bar" style="margin-top: 10px;">
                <div class="progress-fill" style="width: {{ $shelters['occupancy_rate'] }}%;">
                    {{ $shelters['occupancy_rate'] }}%
                </div>
            </div>
        </div>

        <table class="summary-table">
            <tr>
                <td>Total Shelters</td>
                <td>{{ $shelters['total'] }}</td>
            </tr>
            <tr>
                <td>Active Shelters</td>
                <td><span class="badge badge-active">{{ $shelters['active'] }}</span></td>
            </tr>
            <tr>
                <td>Full Shelters</td>
                <td><span class="badge-critical">{{ $shelters['full'] }}</span></td>
            </tr>
            <tr>
                <td>Total Capacity</td>
                <td><strong>{{ $shelters['total_capacity'] }}</strong> people</td>
            </tr>
            <tr>
                <td>Currently Occupied</td>
                <td><strong>{{ $shelters['total_occupied'] }}</strong> people</td>
            </tr>
            <tr>
                <td>Available Space</td>
                <td><strong style="color: #27ae60;">{{ $shelters['available_space'] }}</strong> people</td>
            </tr>
        </table>

        <h4 style="margin-top: 20px; margin-bottom: 10px;">Shelter Details:</h4>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Shelter Name</th>
                    <th>Location</th>
                    <th>Capacity</th>
                    <th>Occupied</th>
                    <th>Available</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($shelters['list'] as $shelter)
                <tr>
                    <td>{{ $shelter->name }}</td>
                    <td>{{ $shelter->city }}</td>
                    <td>{{ $shelter->capacity }}</td>
                    <td>{{ $shelter->current_occupancy }}</td>
                    <td>{{ $shelter->capacity - $shelter->current_occupancy }}</td>
                    <td>
                        <span class="badge badge-{{ strtolower(str_replace(' ', '-', $shelter->status)) }}">
                            {{ $shelter->status }}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Emergency Requests Section -->
    <div class="section">
        <div class="section-title">📋 EMERGENCY REQUESTS SUMMARY</div>
        
        <table class="summary-table">
            <tr>
                <td>Total Requests</td>
                <td>{{ $requests['total'] }}</td>
            </tr>
            <tr>
                <td>Pending Requests</td>
                <td><span class="badge badge-pending">{{ $requests['pending'] }}</span></td>
            </tr>
            <tr>
                <td>Assigned</td>
                <td>{{ $requests['assigned'] }}</td>
            </tr>
            <tr>
                <td>In Progress</td>
                <td>{{ $requests['in_progress'] }}</td>
            </tr>
            <tr>
                <td>Completed</td>
                <td><span class="badge badge-completed">{{ $requests['completed'] }}</span></td>
            </tr>
            <tr>
                <td>Total People Needing Help</td>
                <td><strong>{{ $requests['total_people'] }}</strong> people</td>
            </tr>
        </table>

        <h4 style="margin-top: 20px; margin-bottom: 10px;">Requests by Type:</h4>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Request Type</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($requests['by_type'] as $type => $count)
                <tr>
                    <td>{{ $type }}</td>
                    <td>{{ $count }}</td>
                    <td>{{ $requests['total'] > 0 ? round(($count / $requests['total']) * 100, 1) : 0 }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <h4 style="margin-top: 20px; margin-bottom: 10px;">Requests by Urgency:</h4>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Urgency Level</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($requests['by_urgency'] as $urgency => $count)
                <tr>
                    <td>
                        <span class="badge badge-{{ strtolower($urgency) }}">{{ $urgency }}</span>
                    </td>
                    <td>{{ $count }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- System Statistics -->
    <div class="section">
        <div class="section-title">👥 SYSTEM STATISTICS</div>
        
        <table class="summary-table">
            <tr>
                <td>Total Users</td>
                <td>{{ $users['total'] }}</td>
            </tr>
            <tr>
                <td>Administrators</td>
                <td>{{ $users['admins'] }}</td>
            </tr>
            <tr>
                <td>Citizens</td>
                <td>{{ $users['citizens'] }}</td>
            </tr>
            <tr>
                <td>Relief Workers</td>
                <td>{{ $users['relief_workers'] }}</td>
            </tr>
            <tr>
                <td>Active Users</td>
                <td>{{ $users['active'] }}</td>
            </tr>
        </table>

        <h4 style="margin-top: 20px; margin-bottom: 10px;">Shelter Assignments:</h4>
        <table class="summary-table">
            <tr>
                <td>Total Assignments</td>
                <td>{{ $assignments['total'] }}</td>
            </tr>
            <tr>
                <td>Active Assignments</td>
                <td>{{ $assignments['active'] }}</td>
            </tr>
            <tr>
                <td>Checked In</td>
                <td>{{ $assignments['checked_in'] }}</td>
            </tr>
            <tr>
                <td>Checked Out</td>
                <td>{{ $assignments['checked_out'] }}</td>
            </tr>
        </table>
    </div>

    <!-- Footer -->
    <div class="footer">
        <p><strong>Disaster Alert & Resource Management System</strong></p>
        <p>This report is confidential and for official use only.</p>
        <p>For support, contact: admin@disaster-alert.gov.bd | Emergency Hotline: 999</p>
    </div>
</body>
</html>
